structure:
  readme: ./README.md
  summary: ./SUMMARY.md
redirects:
  "blemish-removal-ipad": "evoto-ipad/chỉnh-sửa-chân-dung/blemish-removal-ipad.md"
  "how-to-use-import-export": "evoto-pc/bắt-đầu/how-to-use-import-export.md"
  "installation-faqs": "faq/liên-quan-đến-cài-đặt-ứng-dụng/installation-faqs.md"
  "vi/anh-evoto": "gia-ca-thanh-toan/ảnh-evoto/anh-evoto.md"
  "vi/auto-import-and-export-vi": "evoto-pc/tự-động-nhập-và-xuất/auto-import-and-export-vi.md"
  "vi/backdrop-changer-ipad-vi": "evoto-ipad/điều-chỉnh-phông-nền/backdrop-changer-ipad-vi.md"
  "vi/backdrop-changer-vi": "evoto-pc/điều-chỉnh-phông-nền/backdrop-changer-vi.md"
  "vi/background-adjustments-ipad-vi": "evoto-ipad/điều-chỉnh-phông-nền/background-adjustments-ipad-vi.md"
  "vi/background-adjustments-vi": "evoto-pc/điều-chỉnh-phông-nền/background-adjustments-vi.md"
  "vi/blemish-removal-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/blemish-removal-ipad-vi.md"
  "vi/blemish-removal-vi": "evoto-pc/chỉnh-sửa-chân-dung/blemish-removal-vi.md"
  "vi/cac-cau-hoi-thuong-gap-ve-tai-khoan-evoto": "cai-dat-tai-khoan/các-câu-hỏi-thường-gặp-về-tài-khoản-evoto/cac-cau-hoi-thuong-gap-ve-tai-khoan-evoto.md"
  "vi/cac-van-de-lien-quan-den-chinh-sua-anh": "faq/liên-quan-đến-chỉnh-sửa-ảnh/cac-van-de-lien-quan-den-chinh-sua-anh.md"
  "vi/cach-dat-duoc-tong-mau-da-dong-deu-trong-evoto": "meo-thu-thuat/liên-quan-đến-các-tính-năng/cach-dat-duoc-tong-mau-da-dong-deu-trong-evoto.md"
  "vi/cach-nhanh-chong-xu-ly-toc-bac-trong-anh-cua-ban-bang-evoto": "meo-thu-thuat/liên-quan-đến-các-tính-năng/cach-nhanh-chong-xu-ly-toc-bac-trong-anh-cua-ban-bang-evoto.md"
  "vi/cach-nhap-tep-xmp-va-cube-vao-evoto": "meo-thu-thuat/hướng-dẫn-cài-đặt/cach-nhap-tep-xmp-va-cube-vao-evoto.md"
  "vi/cai-dat-tai-khoan": "cai-dat-tai-khoan/cài-đặt-tài-khoản/cai-dat-tai-khoan.md"
  "vi/chinh-sua-anh-nhanh-hon-voi-tinh-nang-nhap-chuot-phai-de-mo-anh-bang-evoto": "meo-thu-thuat/qui-trình-chỉnh-sửa-ảnh/chinh-sua-anh-nhanh-hon-voi-tinh-nang-nhap-chuot-phai-de-mo-anh-bang-evoto.md"
  "vi/clothing-adjustment-ipad-vi": "evoto-ipad/làm-đẹp-trang-phục/clothing-adjustment-ipad-vi.md"
  "vi/clothing-adjustment-vi": "evoto-pc/làm-đẹp-trang-phục/clothing-adjustment-vi.md"
  "vi/color-adjustment-feature-modules-vi": "evoto-pc/điều-chỉnh-màu-sắc/color-adjustment-feature-modules-vi.md"
  "vi/color-adjustment-ipad-vi": "evoto-ipad/điều-chỉnh-màu-sắc/color-adjustment-ipad-vi.md"
  "vi/crop-ipad-vi": "evoto-ipad/cắt-và-xoay/crop-ipad-vi.md"
  "vi/crop-vi": "evoto-pc/cắt-và-xoay-ảnh/crop-vi.md"
  "vi/dam-bao-chat-luong-hinh-anh-toi-da-khi-xuat-anh-trong-evoto": "meo-thu-thuat/hướng-dẫn-cài-đặt/dam-bao-chat-luong-hinh-anh-toi-da-khi-xuat-anh-trong-evoto.md"
  "vi/devices-compatibility-overview-ipad-vi": "evoto-ipad/bắt-đầu/devices-compatibility-overview-ipad-vi.md"
  "vi/dieu-chinh-da-trong-evoto-nang-cao-va-hoan-thien-hinh-anh-cua-ban": "meo-thu-thuat/liên-quan-đến-các-tính-năng/dieu-chinh-da-trong-evoto-nang-cao-va-hoan-thien-hinh-anh-cua-ban.md"
  "vi/edit-vi": "evoto-pc/bắt-đầu/edit-vi.md"
  "vi/evoto-for-desktop-wireless-tethering": "evoto-pc/chụp-ảnh-kết-nối-máy-tính/evoto-for-desktop-wireless-tethering.md"
  "vi/evoto-ipad-faq-vi": "faq/câu-hỏi-thường-gặp-về-evoto-ipad/evoto-ipad-faq-vi.md"
  "vi/eyes-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/eyes-ipad-vi.md"
  "vi/eyes-vi": "evoto-pc/chỉnh-sửa-chân-dung/eyes-vi.md"
  "vi/facial-expression-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/facial-expression-ipad-vi.md"
  "vi/facial-expression-vi": "evoto-pc/chỉnh-sửa-chân-dung/facial-expression-vi.md"
  "vi/facial-reshape-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/facial-reshape-ipad-vi.md"
  "vi/facial-reshape-vi": "evoto-pc/chỉnh-sửa-chân-dung/facial-reshape-vi.md"
  "vi/feature-introduction-ai-color-looks-vi": "evoto-pc/điều-chỉnh-màu-sắc/feature-introduction-ai-color-looks-vi.md"
  "vi/feature-introduction-ai-color-match-vi": "evoto-pc/điều-chỉnh-màu-sắc/feature-introduction-ai-color-match-vi.md"
  "vi/feature-introduction-masking-vi": "evoto-pc/điều-chỉnh-màu-sắc/feature-introduction-masking-vi.md"
  "vi/full-body-reshape-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/full-body-reshape-ipad-vi.md"
  "vi/full-body-reshape-vi": "evoto-ipad/chỉnh-sửa-chân-dung/full-body-reshape-vi.md"
  "vi/get-start-vi": "evoto-pc/bắt-đầu/get-start-vi.md"
  "vi/gioi-thieu-tinh-nang-xoa-khuyet-diem-bong-mat-quang-tham": "meo-thu-thuat/liên-quan-đến-các-tính-năng/gioi-thieu-tinh-nang-xoa-khuyet-diem-bong-mat-quang-tham.md"
  "vi/hair-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/hair-ipad-vi.md"
  "vi/hair-vi": "evoto-pc/chỉnh-sửa-chân-dung/hair-vi.md"
  "vi/hands-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/hands-ipad-vi.md"
  "vi/hands-vi": "evoto-pc/chỉnh-sửa-chân-dung/hands-vi.md"
  "vi/hoa-don-vat": "gia-ca-thanh-toan/hóa-đơn-and-vat/hoa-don-vat.md"
  "vi/hoan-thien-quy-trinh-lam-viec-cua-ban-voi-tinh-nang-phoi-mau-ai": "meo-thu-thuat/liên-quan-đến-các-tính-năng/hoan-thien-quy-trinh-lam-viec-cua-ban-voi-tinh-nang-phoi-mau-ai.md"
  "vi/how-to-use-keyboard-shortcut-vi": "evoto-pc/bắt-đầu/how-to-use-keyboard-shortcut-vi.md"
  "vi/how-to-use-languages-ipad-vi": "evoto-ipad/bắt-đầu/how-to-use-languages-ipad-vi.md"
  "vi/how-to-use-languages-vi": "evoto-pc/bắt-đầu/how-to-use-languages-vi.md"
  "vi/how-to-use-preset-ipad-vi": "evoto-ipad/bắt-đầu/how-to-use-preset-ipad-vi.md"
  "vi/how-to-use-preset-vi": "evoto-pc/bắt-đầu/how-to-use-preset-vi.md"
  "vi/how-to-use-setting-vi": "evoto-pc/bắt-đầu/how-to-use-setting-vi.md"
  "vi/how-to-use-settings-ipad-vi": "evoto-ipad/bắt-đầu/how-to-use-settings-ipad-vi.md"
  "vi/how-to-use-sync-the-feature-effect-vi": "evoto-pc/bắt-đầu/how-to-use-sync-the-feature-effect-vi.md"
  "vi/huy-kich-hoat-va-khoi-phuc-tai-khoan": "cai-dat-tai-khoan/xoá-và-khôi-phục-tài-khoản/huy-kich-hoat-va-khoi-phuc-tai-khoan.md"
  "vi/introduce-to-workspace-ipad-vi": "evoto-ipad/bắt-đầu/introduce-to-workspace-ipad-vi.md"
  "vi/kham-pha-tinh-nang-dieu-chinh-mau-sac-theo-thoi-gian-thuc-cua-evoto": "meo-thu-thuat/liên-quan-đến-các-tính-năng/kham-pha-tinh-nang-dieu-chinh-mau-sac-theo-thoi-gian-thuc-cua-evoto.md"
  "vi/library-vi": "evoto-pc/bắt-đầu/library-vi.md"
  "vi/lien-quan-van-de-su-dung": "faq/liên-quan-vấn-đề-sử-dụng/lien-quan-van-de-su-dung.md"
  "vi/ma-giam-gia-evoto": "gia-ca-thanh-toan/mã-giảm-giá/ma-giam-gia-evoto.md"
  "vi/makeup-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/makeup-ipad-vi.md"
  "vi/makeup-vi": "evoto-pc/chỉnh-sửa-chân-dung/makeup-vi.md"
  "vi/nang-tam-buc-anh-cua-ban-voi-cac-mau-phong-cach-ai-cua-evoto": "meo-thu-thuat/liên-quan-đến-các-tính-năng/nang-tam-buc-anh-cua-ban-voi-cac-mau-phong-cach-ai-cua-evoto.md"
  "vi/nang-tam-buc-anh-cua-ban-voi-tinh-nang-trang-diem-nang-cao-cua-evoto": "meo-thu-thuat/liên-quan-đến-các-tính-năng/nang-tam-buc-anh-cua-ban-voi-tinh-nang-trang-diem-nang-cao-cua-evoto.md"
  "vi/nhap-anh-xuat-anh": "faq/liên-quan-đến-nhập-and-xuất-ảnh/nhap-anh-xuat-anh.md"
  "vi/personalized-ai-look": "evoto-pc/điều-chỉnh-màu-sắc/personalized-ai-look.md"
  "vi/pet-body": "evoto-pc/chỉnh-sửa-ảnh-thú-cưng/pet-body.md"
  "vi/pet-eyes": "evoto-pc/chỉnh-sửa-ảnh-thú-cưng/pet-eyes.md"
  "vi/portrait-retouching-feature-module-vi": "evoto-pc/chỉnh-sửa-chân-dung/portrait-retouching-feature-module-vi.md"
  "vi/quan-ly-tai-khoan-nang-cao": "cai-dat-tai-khoan/quản-lý-tài-khoản-nâng-cao/quan-ly-tai-khoan-nang-cao.md"
  "vi/rotate-ipad-vi": "evoto-ipad/cắt-và-xoay/rotate-ipad-vi.md"
  "vi/rotate-vi": "evoto-pc/cắt-và-xoay-ảnh/rotate-vi.md"
  "vi/skin-retouching-vi": "evoto-pc/chỉnh-sửa-chân-dung/skin-retouching-vi.md"
  "vi/sky-replacement-ipad-vi": "evoto-ipad/điều-chỉnh-phông-nền/sky-replacement-ipad-vi.md"
  "vi/sky-replacement-vi": "evoto-pc/điều-chỉnh-phông-nền/sky-replacement-vi.md"
  "vi/su-khac-biet-giua-thay-doi-tong-mau-da-va-lam-sang-da-trong-evoto": "meo-thu-thuat/liên-quan-đến-các-tính-năng/su-khac-biet-giua-thay-doi-tong-mau-da-va-lam-sang-da-trong-evoto.md"
  "vi/teeth-ipad-vi": "evoto-ipad/chỉnh-sửa-chân-dung/teeth-ipad-vi.md"
  "vi/teeth-vi": "evoto-pc/chỉnh-sửa-chân-dung/teeth-vi.md"
  "vi/tethered-shooting-vi": "evoto-pc/chụp-ảnh-kết-nối-máy-tính/tethered-shooting-vi.md"
  "vi/tich-hop-giua-evoto-va-lightroom-classic": "meo-thu-thuat/qui-trình-chỉnh-sửa-ảnh/tich-hop-giua-evoto-va-lightroom-classic.md"
  "vi/tim-hieu-ve-cac-thanh-truot-bi-lam-mo-trong-chuc-nang-chinh-sua-toan-than-y-nghia-va-cach-xu-ly": "meo-thu-thuat/hướng-dẫn-cài-đặt/tim-hieu-ve-cac-thanh-truot-bi-lam-mo-trong-chuc-nang-chinh-sua-toan-than-y-nghia-va-cach-xu-ly.md"
  "vi/tim-ve-cac-chuc-nang-lich-su-trong-evoto-lich-su-chung-lich-su-liquify-va-lich-su-cong-cu-phuc-hoi": "meo-thu-thuat/hướng-dẫn-cài-đặt/tim-ve-cac-chuc-nang-lich-su-trong-evoto-lich-su-chung-lich-su-liquify-va-lich-su-cong-cu-phuc-hoi.md"
  "vi/toi-uu-hoa-hieu-suat-cua-evoto-tang-toc-quy-trinh-chinh-sua-cua-ban": "meo-thu-thuat/hướng-dẫn-cài-đặt/toi-uu-hoa-hieu-suat-cua-evoto-tang-toc-quy-trinh-chinh-sua-cua-ban.md"
  "vi/tool-bar-ipad-vi": "evoto-ipad/bắt-đầu/tool-bar-ipad-vi.md"
  "vi/tool-bar-vi": "evoto-pc/bắt-đầu/tool-bar-vi.md"
  "vi/tu-dong-hoa-quy-trinh-lam-viec-cua-ban-voi-tinh-nang-tu-dong-nhap-xuat": "meo-thu-thuat/qui-trình-chỉnh-sửa-ảnh/tu-dong-hoa-quy-trinh-lam-viec-cua-ban-voi-tinh-nang-tu-dong-nhap-xuat.md"
  "vi/tuy-chinh-chat-luong-xuat-anh-trong-evoto-huong-dan-cac-cai-dat-nang-cao": "meo-thu-thuat/hướng-dẫn-cài-đặt/tuy-chinh-chat-luong-xuat-anh-trong-evoto-huong-dan-cac-cai-dat-nang-cao.md"
  "vi/vietnamese-ver-of-pricing-faq": "gia-ca-thanh-toan/câu-hỏi-thường-gặp-về-gói-ảnh-và-giá-gói-ảnh/vietnamese-ver-of-pricing-faq.md"
  "vi/welcome-to-evoto-ai-ipad-vi": "evoto-ipad/bắt-đầu/welcome-to-evoto-ai-ipad-vi.md"
  "vi/wired-tethered-shooting-ipad-vi": "evoto-ipad/chụp-ảnh-kết-nối/wired-tethered-shooting-ipad-vi.md"
  "vi/wireless-tethered-shooting-ipad-vi": "evoto-ipad/chụp-ảnh-kết-nối/wireless-tethered-shooting-ipad-vi.md"
  "vi/xu-ly-ho-tro-cac-van-de-ve-tai-khoan": "cai-dat-tai-khoan/xử-lý-and-hỗ-trợ-vấn-đề-về-tài-khoản/xu-ly-ho-tro-cac-van-de-ve-tai-khoan.md"
  "vi/xuat-tep-png-voi-nen-trong-suot": "meo-thu-thuat/hướng-dẫn-cài-đặt/xuat-tep-png-voi-nen-trong-suot.md"
