structure:
  readme: ./README.md
  summary: ./SUMMARY.md
redirects:
  "backdrop-changer": "evoto-ipad/ajustes-de-fondo/backdrop-changer.md"
  "es/abrir-con-clic-derecho-en-evoto-edicion-de-imagenes-mas-rapida": "trucos-y-consejos/flujo-de-trabajo/abrir-con-clic-derecho-en-evoto-edicion-de-imagenes-mas-rapida.md"
  "es/atajos-de-teclado": "evoto-ipad/cómo-empezar/atajos-de-teclado.md"
  "es/auto-import-and-export-es": "evoto-pc/importación-y-exportación-automática/auto-import-and-export-es.md"
  "es/backdrop-changer-es": "evoto-pc/ajustes-de-fondo/backdrop-changer-es.md"
  "es/backdrop-changer-ipad-es": "evoto-ipad/ajustes-de-fondo/backdrop-changer-ipad-es.md"
  "es/background-adjustments-es": "evoto-pc/ajustes-de-fondo/background-adjustments-es.md"
  "es/background-adjustments-ipad-es": "evoto-ipad/ajustes-de-fondo/background-adjustments-ipad-es.md"
  "es/blemish-removal-es": "evoto-pc/retoque-de-retrato/blemish-removal-es.md"
  "es/blemish-removal-ipad-es": "evoto-ipad/retoque-de-retrato/blemish-removal-ipad-es.md"
  "es/captura-inalambrica": "evoto-pc/captura-mediante-dispositivos/captura-inalambrica.md"
  "es/clothing-adjustment-ipad-es": "evoto-ipad/retocar-ropa-y-accesorios/clothing-adjustment-ipad-es.md"
  "es/codigos-promocionales": "precios-facturacion/códigos-promocionales/codigos-promocionales.md"
  "es/color-adjustment-feature-modules-es": "evoto-pc/ajustes-de-color/color-adjustment-feature-modules-es.md"
  "es/color-adjustment-ipad-es": "evoto-ipad/ajustes-de-color/color-adjustment-ipad-es.md"
  "es/como-abordar-rapidamente-el-cabello-blanco-en-tus-fotos": "trucos-y-consejos/relacionado-con-funciones/como-abordar-rapidamente-el-cabello-blanco-en-tus-fotos.md"
  "es/como-ahorrar-tiempo-con-la-coincidencia-de-estilos-en-lote-sincronizacion-y-preajustes-en-evoto": "trucos-y-consejos/flujo-de-trabajo/como-ahorrar-tiempo-con-la-coincidencia-de-estilos-en-lote-sincronizacion-y-preajustes-en-evoto.md"
  "es/como-ajustar-el-tono-de-piel-en-evoto": "trucos-y-consejos/relacionado-con-funciones/como-ajustar-el-tono-de-piel-en-evoto.md"
  "es/como-automatizar-tu-flujo-de-trabajo-con-importacion-y-exportacion-automatica": "trucos-y-consejos/flujo-de-trabajo/como-automatizar-tu-flujo-de-trabajo-con-importacion-y-exportacion-automatica.md"
  "es/como-blanquear-los-dientes-en-evoto-en-3-formas-rapidas": "trucos-y-consejos/relacionado-con-funciones/como-blanquear-los-dientes-en-evoto-en-3-formas-rapidas.md"
  "es/como-corregir-sonrisas-en-evoto": "trucos-y-consejos/relacionado-con-funciones/como-corregir-sonrisas-en-evoto.md"
  "es/como-dar-vida-a-los-retratos-con-las-herramientas-de-retoque-de-ojos": "trucos-y-consejos/relacionado-con-funciones/como-dar-vida-a-los-retratos-con-las-herramientas-de-retoque-de-ojos.md"
  "es/como-dominar-el-retoque-de-piel-para-resultados-naturales": "trucos-y-consejos/relacionado-con-funciones/como-dominar-el-retoque-de-piel-para-resultados-naturales.md"
  "es/como-dominar-las-funciones-de-historial-de-evoto": "trucos-y-consejos/guías-de-configuración/como-dominar-las-funciones-de-historial-de-evoto.md"
  "es/como-elegir-entre-cambio-de-tono-de-piel-y-luminosidad-de-piel": "trucos-y-consejos/relacionado-con-funciones/como-elegir-entre-cambio-de-tono-de-piel-y-luminosidad-de-piel.md"
  "es/como-elevar-tus-fotos-con-ai-color-looks-de-evoto": "trucos-y-consejos/relacionado-con-funciones/como-elevar-tus-fotos-con-ai-color-looks-de-evoto.md"
  "es/como-eliminar-los-ojos-cansados-con-la-eliminacion-rapida-de-bolsas": "trucos-y-consejos/relacionado-con-funciones/como-eliminar-los-ojos-cansados-con-la-eliminacion-rapida-de-bolsas.md"
  "es/como-importar-archivos-xmp-y-cube-en-evoto": "trucos-y-consejos/guías-de-configuración/como-importar-archivos-xmp-y-cube-en-evoto.md"
  "es/como-lograr-un-tono-de-piel-uniforme-en-evoto": "trucos-y-consejos/relacionado-con-funciones/como-lograr-un-tono-de-piel-uniforme-en-evoto.md"
  "es/como-mejorar-tu-flujo-de-trabajo-con-ai-color-match": "trucos-y-consejos/relacionado-con-funciones/como-mejorar-tu-flujo-de-trabajo-con-ai-color-match.md"
  "es/como-obtener-una-foto-con-fondo-limpio-en-evoto": "trucos-y-consejos/relacionado-con-funciones/como-obtener-una-foto-con-fondo-limpio-en-evoto.md"
  "es/como-optimizar-el-rendimiento-de-evoto": "trucos-y-consejos/guías-de-configuración/como-optimizar-el-rendimiento-de-evoto.md"
  "es/como-personalizar-la-calidad-de-exportacion-de-imagen-en-evoto": "trucos-y-consejos/guías-de-configuración/como-personalizar-la-calidad-de-exportacion-de-imagen-en-evoto.md"
  "es/como-puedo-usar-exportaciones-sin-creditos": "evoto-pc/cómo-empezar/como-puedo-usar-exportaciones-sin-creditos.md"
  "es/como-recuperar-las-pecas-y-lunares-que-evoto-elimino": "trucos-y-consejos/relacionado-con-funciones/como-recuperar-las-pecas-y-lunares-que-evoto-elimino.md"
  "es/como-reemplazar-el-cielo-en-evoto": "trucos-y-consejos/relacionado-con-funciones/como-reemplazar-el-cielo-en-evoto.md"
  "es/como-usar-la-funcion-de-maquillaje-en-evoto": "trucos-y-consejos/relacionado-con-funciones/como-usar-la-funcion-de-maquillaje-en-evoto.md"
  "es/como-usar-los-ajustes-de-color-en-tiempo-real": "trucos-y-consejos/relacionado-con-funciones/como-usar-los-ajustes-de-color-en-tiempo-real.md"
  "es/configuracion-y-seguridad": "cuenta/configuración-y-seguridad/configuracion-y-seguridad.md"
  "es/credits": "precios-facturacion/créditos/credits.md"
  "es/crop-es": "evoto-pc/recortar-y-rotar/crop-es.md"
  "es/crop-ipad-es": "evoto-ipad/recortar-y-rotar/crop-ipad-es.md"
  "es/desactivacion-y-recuperacion": "cuenta/desactivación-y-recuperación/desactivacion-y-recuperacion.md"
  "es/devices-compatibility-overview-ipad-es": "evoto-ipad/cómo-empezar/devices-compatibility-overview-ipad-es.md"
  "es/edit-es": "evoto-pc/cómo-empezar/edit-es.md"
  "es/eliminacion-de-imperfecciones-circulos-oscuros-y-bolsas-bajo-los-ojos": "trucos-y-consejos/relacionado-con-funciones/eliminacion-de-imperfecciones-circulos-oscuros-y-bolsas-bajo-los-ojos.md"
  "es/eyes-ipad-es": "evoto-ipad/retoque-de-retrato/eyes-ipad-es.md"
  "es/facial-expression-es": "evoto-pc/retoque-de-retrato/facial-expression-es.md"
  "es/facial-expression-ipad-es": "evoto-ipad/retoque-de-retrato/facial-expression-ipad-es.md"
  "es/facial-reshape-es": "evoto-pc/retoque-de-retrato/facial-reshape-es.md"
  "es/facial-reshape-ipad-es": "evoto-ipad/retoque-de-retrato/facial-reshape-ipad-es.md"
  "es/factura-e-iva": "precios-facturacion/factura-e-iva/factura-e-iva.md"
  "es/feature-introduction-ai-color-looks-es": "evoto-pc/ajustes-de-color/feature-introduction-ai-color-looks-es.md"
  "es/feature-introduction-ai-color-match-es": "evoto-pc/ajustes-de-color/feature-introduction-ai-color-match-es.md"
  "es/feature-introduction-masking-es": "evoto-pc/ajustes-de-color/feature-introduction-masking-es.md"
  "es/full-body-reshape-es": "evoto-pc/retoque-de-retrato/full-body-reshape-es.md"
  "es/full-body-reshape-ipad-es": "evoto-ipad/retoque-de-retrato/full-body-reshape-ipad-es.md"
  "es/gestion-avanzada": "cuenta/gestión-avanzada/gestion-avanzada.md"
  "es/get-start-es": "evoto-pc/cómo-empezar/get-start-es.md"
  "es/hair-es": "evoto-pc/retoque-de-retrato/hair-es.md"
  "es/hair-ipad-es": "evoto-ipad/retoque-de-retrato/hair-ipad-es.md"
  "es/hands-es": "evoto-pc/retoque-de-retrato/hands-es.md"
  "es/home/evoto-ipad": "evoto-ipad/cómo-empezar/evoto-ipad.md"
  "es/how-to-use-import-export-es": "evoto-pc/cómo-empezar/how-to-use-import-export-es.md"
  "es/how-to-use-keyboard-shortcut-es": "evoto-pc/cómo-empezar/how-to-use-keyboard-shortcut-es.md"
  "es/how-to-use-languages-es": "evoto-pc/cómo-empezar/how-to-use-languages-es.md"
  "es/how-to-use-preset-es": "evoto-pc/cómo-empezar/how-to-use-preset-es.md"
  "es/how-to-use-preset-ipad-es": "evoto-ipad/cómo-empezar/how-to-use-preset-ipad-es.md"
  "es/how-to-use-setting-es": "evoto-pc/cómo-empezar/how-to-use-setting-es.md"
  "es/how-to-use-settings-ipad-es": "evoto-ipad/cómo-empezar/how-to-use-settings-ipad-es.md"
  "es/how-to-use-sync-the-feature-effect-es": "evoto-pc/cómo-empezar/how-to-use-sync-the-feature-effect-es.md"
  "es/importar-y-exportar-archivos-lrcat-entre-lightroom-classic-y-evoto": "trucos-y-consejos/flujo-de-trabajo/importar-y-exportar-archivos-lrcat-entre-lightroom-classic-y-evoto.md"
  "es/introduce-to-workspace-ipad-es": "evoto-ipad/cómo-empezar/introduce-to-workspace-ipad-es.md"
  "es/library-es": "evoto-pc/cómo-empezar/library-es.md"
  "es/makeup-es": "evoto-pc/retoque-de-retrato/makeup-es.md"
  "es/makeup-ipad-es": "evoto-ipad/retoque-de-retrato/makeup-ipad-es.md"
  "es/paquete-de-pago-por-uso": "precios-facturacion/paquete-de-pago-por-uso/paquete-de-pago-por-uso.md"
  "es/plan-de-suscripcion": "precios-facturacion/plan-de-suscripción/plan-de-suscripcion.md"
  "es/por-que-algunos-controles-deslizantes-estan-desactivados-en-remodelacion-de-cuerpo-completo": "trucos-y-consejos/guías-de-configuración/por-que-algunos-controles-deslizantes-estan-desactivados-en-remodelacion-de-cuerpo-completo.md"
  "es/portrait-retouching-feature-module-es": "evoto-pc/retoque-de-retrato/portrait-retouching-feature-module-es.md"
  "es/portrait-retouching-ipad-es": "evoto-ipad/retoque-de-retrato/portrait-retouching-ipad-es.md"
  "es/preguntas-frecuentes": "precios-facturacion/preguntas-frecuentes/preguntas-frecuentes.md"
  "es/preguntas-frecuentes-de-evoto-ipad": "preguntas-frecuentes/preguntas-frecuentes-de-evoto-ipad/preguntas-frecuentes-de-evoto-ipad.md"
  "es/preguntas-frecuentes-sobre-cuenta": "cuenta/preguntas-frecuentes/preguntas-frecuentes-sobre-cuenta.md"
  "es/preguntas-frecuentes-sobre-instalacion": "preguntas-frecuentes/relacionado-con-instalación/preguntas-frecuentes-sobre-instalacion.md"
  "es/recursos-adicionales-y-participacion-en-la-comunidad": "preguntas-frecuentes/recursos-adicionales-y-comunidad/recursos-adicionales-y-participacion-en-la-comunidad.md"
  "es/relacionado-con-edicion": "preguntas-frecuentes/relacionado-con-edición/relacionado-con-edicion.md"
  "es/relacionado-con-importacion-y-exportacion": "preguntas-frecuentes/relacionado-con-importación-y-exportación/relacionado-con-importacion-y-exportacion.md"
  "es/relacionado-con-uso": "preguntas-frecuentes/relacionado-con-uso/relacionado-con-uso.md"
  "es/rotate-es": "evoto-pc/recortar-y-rotar/rotate-es.md"
  "es/rotate-ipad-es": "evoto-ipad/recortar-y-rotar/rotate-ipad-es.md"
  "es/skin-retouching-es": "evoto-pc/retoque-de-retrato/skin-retouching-es.md"
  "es/skin-retouching-ipad-es": "evoto-ipad/retoque-de-retrato/skin-retouching-ipad-es.md"
  "es/sky-replacement-es": "evoto-pc/ajustes-de-fondo/sky-replacement-es.md"
  "es/sky-replacement-ipad-es": "evoto-ipad/ajustes-de-fondo/sky-replacement-ipad-es.md"
  "es/solucion-de-problemas-y-asistencia-de-cuenta": "cuenta/solución-de-problemas-y-soporte/solucion-de-problemas-y-asistencia-de-cuenta.md"
  "es/teeth-es": "evoto-pc/retoque-de-retrato/teeth-es.md"
  "es/teeth-ipad-es": "evoto-ipad/retoque-de-retrato/teeth-ipad-es.md"
  "es/tethered-shooting-es": "evoto-pc/captura-mediante-dispositivos/tethered-shooting-es.md"
  "es/tethered-shooting-supported-camera-model-es": "evoto-pc/captura-mediante-dispositivos/tethered-shooting-supported-camera-model-es.md"
  "es/tool-bar-es": "evoto-pc/cómo-empezar/tool-bar-es.md"
  "es/welcome-to-evoto-ai-ipad-es": "evoto-ipad/cómo-empezar/welcome-to-evoto-ai-ipad-es.md"
  "es/wired-tethered-shooting-ipad-es": "evoto-ipad/captura-mediante-dispositivos/wired-tethered-shooting-ipad-es.md"
  "es/wireless-tethered-shooting-ipad-es": "evoto-ipad/captura-mediante-dispositivos/wireless-tethered-shooting-ipad-es.md"
  "eyes": "evoto-pc/retoque-de-retrato/eyes.md"
  "feature-introduction-masking": "evoto-pc/ajustes-de-color/feature-introduction-masking.md"
  "how-to-use-languages-ipad": "evoto-ipad/cómo-empezar/how-to-use-languages-ipad.md"
  "how-to-use-preset-ipad": "evoto-ipad/cómo-empezar/how-to-use-preset-ipad.md"
  "pricing-faq": "precios-facturacion/preguntas-frecuentes/pricing-faq.md"
  "tool-bar-ipad": "evoto-ipad/cómo-empezar/tool-bar-ipad.md"
