structure:
  readme: ./README.md
  summary: ./SUMMARY.md
redirects:
  "backdrop-changer": "evoto-pc/ajustes-de-fundo/backdrop-changer.md"
  "blemish-removal-ipad": "evoto-ipad/retoque-de-retrato/blemish-removal-ipad.md"
  "eyes": "evoto-ipad/retoque-de-retrato/eyes.md"
  "how-to-use-keyboard-shortcut": "evoto-pc/como-começar/how-to-use-keyboard-shortcut.md"
  "pt-br/ajustes-de-roupas-e-acessorios": "evoto-pc/ajustes-de-roupas-e-acessórios/ajustes-de-roupas-e-acessorios.md"
  "pt-br/animal-de-estimacao-olhos": "evoto-pc/animal-de-estimação/animal-de-estimacao-olhos.md"
  "pt-br/animal-de-estimacao-retoque-corporal": "evoto-pc/animal-de-estimação/animal-de-estimacao-retoque-corporal.md"
  "pt-br/atalhos-de-teclado": "evoto-pc/como-começar/atalhos-de-teclado.md"
  "pt-br/atalhos-de-teclado-2": "evoto-ipad/como-começar/atalhos-de-teclado-2.md"
  "pt-br/barra-de-ferramentas": "evoto-pc/como-começar/barra-de-ferramentas.md"
  "pt-br/captura-com-camera-vinculada-conexao-com-fio": "evoto-pc/captura-vinculada/captura-com-camera-vinculada-conexao-com-fio.md"
  "pt-br/captura-com-camera-vinculada-conexao-sem-fio": "evoto-pc/captura-vinculada/captura-com-camera-vinculada-conexao-sem-fio.md"
  "pt-br/captura-com-camera-vinculada-modelos-de-camaras-compativeis": "evoto-pc/captura-vinculada/captura-com-camera-vinculada-modelos-de-camaras-compativeis.md"
  "pt-br/codigos-promocionais": "preco-e-faturamento/perguntas-frequentes-sobre-cupons-e-códigos-promocionais/codigos-promocionais.md"
  "pt-br/comecar-a-usar-evoto": "evoto-pc/como-começar/comecar-a-usar-evoto.md"
  "pt-br/como-ajustar-o-tom-de-pele-no-evoto": "dicas-e-truques/recurso-relevante/como-ajustar-o-tom-de-pele-no-evoto.md"
  "pt-br/como-alcancar-a-retoque-de-pele-para-resultados-naturais": "dicas-e-truques/recurso-relevante/como-alcancar-a-retoque-de-pele-para-resultados-naturais.md"
  "pt-br/como-alcancar-um-tom-de-pele-uniforme-e-radiante-no-evoto": "dicas-e-truques/recurso-relevante/como-alcancar-um-tom-de-pele-uniforme-e-radiante-no-evoto.md"
  "pt-br/como-as-fotos-sao-compartilhadas-no-instant": "instant/configuração/como-as-fotos-sao-compartilhadas-no-instant.md"
  "pt-br/como-as-fotos-sao-processadas-no-instant": "instant/configuração/como-as-fotos-sao-processadas-no-instant.md"
  "pt-br/como-automatizar-seu-fluxo-de-trabalho-com-importacao-exportacao-automaticas": "dicas-e-truques/fluxo-de-trabalho/como-automatizar-seu-fluxo-de-trabalho-com-importacao-exportacao-automaticas.md"
  "pt-br/como-clarear-os-dentes-no-evoto-em-3-passos-rapidos": "dicas-e-truques/recurso-relevante/como-clarear-os-dentes-no-evoto-em-3-passos-rapidos.md"
  "pt-br/como-corrigir-rapidamente-cabelos-brancos": "dicas-e-truques/recurso-relevante/como-corrigir-rapidamente-cabelos-brancos.md"
  "pt-br/como-corrigir-sorrisos-no-evoto": "dicas-e-truques/recurso-relevante/como-corrigir-sorrisos-no-evoto.md"
  "pt-br/como-dar-vida-aos-retratos-com-as-ferramentas-de-olhos-do-evoto": "dicas-e-truques/recurso-relevante/como-dar-vida-aos-retratos-com-as-ferramentas-de-olhos-do-evoto.md"
  "pt-br/como-economizar-tempo-com-correspondencia-de-estilo-em-lote-sincronizacao-e-predefinicao-no-evoto": "dicas-e-truques/fluxo-de-trabalho/como-economizar-tempo-com-correspondencia-de-estilo-em-lote-sincronizacao-e-predefinicao-no-evoto.md"
  "pt-br/como-eliminar-olheiras-e-olhos-cansados-com-a-remocao-rapida-de-bolsas-sob-os-olhos-no-evoto": "dicas-e-truques/recurso-relevante/como-eliminar-olheiras-e-olhos-cansados-com-a-remocao-rapida-de-bolsas-sob-os-olhos-no-evoto.md"
  "pt-br/como-escolher-entre-alteracao-da-cor-da-pele-e-radiancia-da-pele-no-evoto": "dicas-e-truques/recurso-relevante/como-escolher-entre-alteracao-da-cor-da-pele-e-radiancia-da-pele-no-evoto.md"
  "pt-br/como-escolher-entre-as-ferramentas-de-aprimoramento-da-area-dos-olhos": "dicas-e-truques/recurso-relevante/como-escolher-entre-as-ferramentas-de-aprimoramento-da-area-dos-olhos.md"
  "pt-br/como-importar-arquivos-xmp-e-cube-no-evoto": "dicas-e-truques/guia-de-configurações/como-importar-arquivos-xmp-e-cube-no-evoto.md"
  "pt-br/como-integrar-o-evoto-de-forma-integrada-ao-lightroom-classic": "dicas-e-truques/fluxo-de-trabalho/como-integrar-o-evoto-de-forma-integrada-ao-lightroom-classic.md"
  "pt-br/como-obter-um-fundo-limpo-no-evoto": "dicas-e-truques/recurso-relevante/como-obter-um-fundo-limpo-no-evoto.md"
  "pt-br/como-otimizar-o-desempenho-do-evoto-e-acelerar-seu-fluxo-de-edicao": "dicas-e-truques/guia-de-configurações/como-otimizar-o-desempenho-do-evoto-e-acelerar-seu-fluxo-de-edicao.md"
  "pt-br/como-otimizar-seu-fluxo-de-trabalho-com-correspondencia-de-cor-por-ia": "dicas-e-truques/recurso-relevante/como-otimizar-seu-fluxo-de-trabalho-com-correspondencia-de-cor-por-ia.md"
  "pt-br/como-personalizar-a-qualidade-de-exportacao-de-imagens-no-evoto": "dicas-e-truques/guia-de-configurações/como-personalizar-a-qualidade-de-exportacao-de-imagens-no-evoto.md"
  "pt-br/como-restaurar-sardas-moles-removidas-pelo-evoto": "dicas-e-truques/recurso-relevante/como-restaurar-sardas-moles-removidas-pelo-evoto.md"
  "pt-br/como-substituir-o-ceu-no-evoto": "dicas-e-truques/recurso-relevante/como-substituir-o-ceu-no-evoto.md"
  "pt-br/como-usar-o-recurso-de-maquiagem-no-evoto": "dicas-e-truques/recurso-relevante/como-usar-o-recurso-de-maquiagem-no-evoto.md"
  "pt-br/como-usar-o-recurso-editar-em-no-lightroom-classic": "dicas-e-truques/fluxo-de-trabalho/como-usar-o-recurso-editar-em-no-lightroom-classic.md"
  "pt-br/como-utilizar-ajustes-de-cor-em-tempo-real": "dicas-e-truques/recurso-relevante/como-utilizar-ajustes-de-cor-em-tempo-real.md"
  "pt-br/como-utilizar-secao-de-historico-no-evoto": "dicas-e-truques/guia-de-configurações/como-utilizar-secao-de-historico-no-evoto.md"
  "pt-br/como-valorizar-suas-fotos-com-os-looks-de-cor-por-ia-do-evoto": "dicas-e-truques/recurso-relevante/como-valorizar-suas-fotos-com-os-looks-de-cor-por-ia-do-evoto.md"
  "pt-br/compartilhamento-de-fotos-recurso-find-me": "instant/recursos-em-detalhes/compartilhamento-de-fotos-recurso-find-me.md"
  "pt-br/conectando-sua-camera-ao-seu-celular": "instant/configuração/conectando-sua-camera-ao-seu-celular.md"
  "pt-br/configuracoes-de-sincronizacao": "evoto-pc/como-começar/configuracoes-de-sincronizacao.md"
  "pt-br/configuracoes-do-sistema": "evoto-pc/como-começar/configuracoes-do-sistema.md"
  "pt-br/configuracoes-e-seguranca-da-conta-evoto": "configuracoes-da-conta/configurações-e-segurança-da-conta-evoto/configuracoes-e-seguranca-da-conta-evoto.md"
  "pt-br/correspondencia-de-cor-por-ia": "evoto-pc/ajustes-de-cor/correspondencia-de-cor-por-ia.md"
  "pt-br/corte": "evoto-pc/corte-and-rotação/corte.md"
  "pt-br/criando-um-novo-projeto": "instant/configuração/criando-um-novo-projeto.md"
  "pt-br/design-de-galerias": "instant/recursos-em-detalhes/design-de-galerias.md"
  "pt-br/edicao-com-ia-no-evoto-instant": "instant/recursos-em-detalhes/edicao-com-ia-no-evoto-instant.md"
  "pt-br/evoto-creditos": "preco-e-faturamento/evoto-créditos/evoto-creditos.md"
  "pt-br/evoto-para-ipad-perguntas-frequentes": "perguntas-frequentes/evoto-para-ipad--perguntas-frequentes/evoto-para-ipad-perguntas-frequentes.md"
  "pt-br/faturas-e-iva-invoice-vat": "preco-e-faturamento/faturas-e-iva-invoice-and-vat/faturas-e-iva-invoice-vat.md"
  "pt-br/gerenciamento-de-conta-perfis-funcoes-e-exclusao": "configuracoes-da-conta/gerenciamento-de-conta-perfis-funções-e-exclusão/gerenciamento-de-conta-perfis-funcoes-e-exclusao.md"
  "pt-br/gerenciar-seus-projetos": "instant/recursos-em-detalhes/gerenciar-seus-projetos.md"
  "pt-br/idioma-do-sistema": "evoto-pc/como-começar/idioma-do-sistema.md"
  "pt-br/importacao-e-exportacao-automaticas-pasta-monitorada": "evoto-pc/importação-e-exportação-automáticas/importacao-e-exportacao-automaticas-pasta-monitorada.md"
  "pt-br/importacao-exportacao": "evoto-pc/como-começar/importacao-exportacao.md"
  "pt-br/integracao-com-o-instant": "instant/configuração/integracao-com-o-instant.md"
  "pt-br/introducao-ao-sistema": "instant/configuração/introducao-ao-sistema.md"
  "pt-br/ipad-ajustes-de-fundo": "evoto-ipad/ajustes-de-fundo/ipad-ajustes-de-fundo.md"
  "pt-br/ipad-ajustes-de-roupas": "evoto-ipad/ajustes-de-roupa-e-acessórios/ipad-ajustes-de-roupas.md"
  "pt-br/ipad-barra-de-ferramentas": "evoto-ipad/como-começar/ipad-barra-de-ferramentas.md"
  "pt-br/ipad-captura-vinculada-por-cabo": "evoto-ipad/captura-vinculada/ipad-captura-vinculada-por-cabo.md"
  "pt-br/ipad-captura-vinculada-sem-fio": "evoto-ipad/captura-vinculada/ipad-captura-vinculada-sem-fio.md"
  "pt-br/ipad-configuracoes-do-sistema": "evoto-ipad/como-começar/ipad-configuracoes-do-sistema.md"
  "pt-br/ipad-corte": "evoto-ipad/corte-and-rotação/ipad-corte.md"
  "pt-br/ipad-espaco-de-trabalho-do-projeto": "evoto-ipad/como-começar/ipad-espaco-de-trabalho-do-projeto.md"
  "pt-br/ipad-idioma": "evoto-ipad/como-começar/ipad-idioma.md"
  "pt-br/ipad-introducao": "evoto-ipad/como-começar/ipad-introducao.md"
  "pt-br/ipad-modelos-compativeis": "evoto-ipad/como-começar/ipad-modelos-compativeis.md"
  "pt-br/ipad-modulo-de-ajustes-de-cor": "evoto-ipad/ajustes-de-cor/ipad-modulo-de-ajustes-de-cor.md"
  "pt-br/ipad-modulo-de-retoque-de-retrato": "evoto-ipad/retoque-de-retrato/ipad-modulo-de-retoque-de-retrato.md"
  "pt-br/ipad-predefinicoes": "evoto-ipad/como-começar/ipad-predefinicoes.md"
  "pt-br/ipad-retoque-de-retrato-cabelos": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-cabelos.md"
  "pt-br/ipad-retoque-de-retrato-dentes": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-dentes.md"
  "pt-br/ipad-retoque-de-retrato-expressao-facial": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-expressao-facial.md"
  "pt-br/ipad-retoque-de-retrato-maos": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-maos.md"
  "pt-br/ipad-retoque-de-retrato-maquiagem": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-maquiagem.md"
  "pt-br/ipad-retoque-de-retrato-remodelacao-corporal-completa": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-remodelacao-corporal-completa.md"
  "pt-br/ipad-retoque-de-retrato-remodelacao-facial": "evoto-ipad/retoque-de-retrato/ipad-retoque-de-retrato-remodelacao-facial.md"
  "pt-br/ipad-rotacao": "evoto-ipad/corte-and-rotação/ipad-rotacao.md"
  "pt-br/ipad-substituicao-de-ceu": "evoto-ipad/ajustes-de-fundo/ipad-substituicao-de-ceu.md"
  "pt-br/ipad-trocador-de-fundo": "evoto-ipad/ajustes-de-fundo/ipad-trocador-de-fundo.md"
  "pt-br/laboratorio-de-ia": "evoto-pc/como-começar/laboratorio-de-ia.md"
  "pt-br/looks-de-cor-por-ia": "evoto-pc/ajustes-de-cor/looks-de-cor-por-ia.md"
  "pt-br/mascaras": "evoto-pc/ajustes-de-cor/mascaras.md"
  "pt-br/modo-participante-organizacao-inteligente-por-qr-code": "instant/recursos-em-detalhes/modo-participante-organizacao-inteligente-por-qr-code.md"
  "pt-br/outras-perguntas-frequentes": "perguntas-frequentes/outras-perguntas-frequentes/outras-perguntas-frequentes.md"
  "pt-br/pagina-de-visualizacao-de-imagem": "instant/recursos-em-detalhes/pagina-de-visualizacao-de-imagem.md"
  "pt-br/pague-conforme-o-uso": "preco-e-faturamento/plano-de-pague-conforme-o-uso/pague-conforme-o-uso.md"
  "pt-br/perguntas-frequentes-sobre-a-assinatura-mensal-do-evoto-para-ipad": "preco-e-faturamento/perguntas-frequentes-sobre-a-assinatura-mensal-do-evoto-para-ipad/perguntas-frequentes-sobre-a-assinatura-mensal-do-evoto-para-ipad.md"
  "pt-br/perguntas-frequentes-sobre-conta": "configuracoes-da-conta/perguntas-frequentes-sobre-conta/perguntas-frequentes-sobre-conta.md"
  "pt-br/perguntas-frequentes-sobre-edicao": "perguntas-frequentes/perguntas-frequentes-sobre-edição/perguntas-frequentes-sobre-edicao.md"
  "pt-br/perguntas-frequentes-sobre-importacao-e-exportacao": "perguntas-frequentes/perguntas-frequentes-sobre-importação-and-exportação/perguntas-frequentes-sobre-importacao-e-exportacao.md"
  "pt-br/perguntas-frequentes-sobre-precos": "preco-e-faturamento/perguntas-frequentes-sobre-preços/perguntas-frequentes-sobre-precos.md"
  "pt-br/planos-de-assinatura-anual": "preco-e-faturamento/planos-de-assinatura-anual/planos-de-assinatura-anual.md"
  "pt-br/porque-alguns-sliders-estao-desativados-na-remodelacao-corporal-completa": "dicas-e-truques/guia-de-configurações/porque-alguns-sliders-estao-desativados-na-remodelacao-corporal-completa.md"
  "pt-br/predefinicoes": "evoto-pc/como-começar/predefinicoes.md"
  "pt-br/preparacao-de-hardware": "instant/configuração/preparacao-de-hardware.md"
  "pt-br/reconhecimento-facial-por-ia": "evoto-pc/retoque-de-retrato/reconhecimento-facial-por-ia.md"
  "pt-br/recurso-ajustes-de-cor": "evoto-pc/ajustes-de-cor/recurso-ajustes-de-cor.md"
  "pt-br/recurso-ajustes-de-fundo-ajustes-de-fundo": "evoto-pc/ajustes-de-fundo/recurso-ajustes-de-fundo-ajustes-de-fundo.md"
  "pt-br/recurso-ajustes-de-fundo-substituicao-de-ceu": "evoto-pc/ajustes-de-fundo/recurso-ajustes-de-fundo-substituicao-de-ceu.md"
  "pt-br/recurso-ajustes-de-fundo-trocador-de-fundo": "evoto-pc/ajustes-de-fundo/recurso-ajustes-de-fundo-trocador-de-fundo.md"
  "pt-br/recursos-adicionais-suporte": "perguntas-frequentes/recursos-adicionais-and-suporte/recursos-adicionais-suporte.md"
  "pt-br/retoque-de-pele": "evoto-ipad/retoque-de-retrato/retoque-de-pele.md"
  "pt-br/retoque-de-retrato-cabelos": "evoto-pc/retoque-de-retrato/retoque-de-retrato-cabelos.md"
  "pt-br/retoque-de-retrato-dentes": "evoto-pc/retoque-de-retrato/retoque-de-retrato-dentes.md"
  "pt-br/retoque-de-retrato-expressao-facial": "evoto-pc/retoque-de-retrato/retoque-de-retrato-expressao-facial.md"
  "pt-br/retoque-de-retrato-maos": "evoto-pc/retoque-de-retrato/retoque-de-retrato-maos.md"
  "pt-br/retoque-de-retrato-maquiagem": "evoto-pc/retoque-de-retrato/retoque-de-retrato-maquiagem.md"
  "pt-br/retoque-de-retrato-olhos": "evoto-pc/retoque-de-retrato/retoque-de-retrato-olhos.md"
  "pt-br/retoque-de-retrato-remocao-de-manchas": "evoto-pc/retoque-de-retrato/retoque-de-retrato-remocao-de-manchas.md"
  "pt-br/retoque-de-retrato-remodelacao-corporal-completa": "evoto-pc/retoque-de-retrato/retoque-de-retrato-remodelacao-corporal-completa.md"
  "pt-br/retoque-de-retrato-remodelacao-facial": "evoto-pc/retoque-de-retrato/retoque-de-retrato-remodelacao-facial.md"
  "pt-br/retoque-de-retrato-retoque-de-pele": "evoto-pc/retoque-de-retrato/retoque-de-retrato-retoque-de-pele.md"
  "pt-br/rotacao": "evoto-pc/corte-and-rotação/rotacao.md"
  "pt-br/selecao-com-ia-ai-culling-no-evoto-instant": "instant/recursos-em-detalhes/selecao-com-ia-ai-culling-no-evoto-instant.md"
  "pt-br/solucao-de-problemas-da-conta": "configuracoes-da-conta/solução-de-problemas-da-conta/solucao-de-problemas-da-conta.md"
  "pt-br/solucao-de-problemas-de-instalacao-conflitos-com-antivirus": "perguntas-frequentes/solução-de-problemas-de-instalação-and-conflitos-com-antivírus/solucao-de-problemas-de-instalacao-conflitos-com-antivirus.md"
  "pt-br/suporte-a-multiplos-idiomas": "instant/configuração/suporte-a-multiplos-idiomas.md"
  "pt-br/visao-geral-do-espaco-de-trabalho-biblioteca": "evoto-pc/como-começar/visao-geral-do-espaco-de-trabalho-biblioteca.md"
  "pt-br/visao-geral-do-espaco-de-trabalho-editar": "evoto-pc/como-começar/visao-geral-do-espaco-de-trabalho-editar.md"
  "school-photography-workflow-from-roster-to-revenue": "instant/configuração/school-photography-workflow-from-roster-to-revenue.md"
